global:
  scrape_interval: 15s  # Por padrão, o alvo será coletado a cada 15 segundos

# Carrega arquivo com as regras dos alertas criados
rule_files:
  - "alert.rules"

scrape_configs:

  - job_name: 'prometheus'

    scrape_interval: 5s

    metrics_path: /metrics # Endpoint padrão para a coleta das métricas
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node_exporter'
    scrape_interval: 5s
      - targets: ['node_exporter:9100']
        labels:
          alias: webserver

# Integrando o alertmanager com o prometheus
alerting:
  alertmanager:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'